"""Build a working bridge from nothing: config, secrets, venv, launcher.

``setup_wizard`` edits a config that already exists. This one creates the
whole set from an empty directory, because the first-run problem is
different: an operator with no config has nothing to edit, and the
interesting decisions (which backend, which interface, which direction) all
have to be made before a file can be written at all.

The rendering functions are pure and take a single ``Answers``. That split is
deliberate -- prompting cannot be tested, but every byte that lands on disk
can be, and those bytes are the part that has to be right.

Secrets never enter the YAML. They are written to a mode-0600 env file, and
the config refers to them as ``${ZELLO_...}``, so a config can be pasted into
an issue without leaking an account.
"""

from __future__ import annotations

import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .setup_wizard import (
    Choice,
    SelectionAborted,
    _confirm,
    _prompt_choice,
    _prompt_port,
    _prompt_text,
    render_asl_instructions,
    yaml_scalar,
)

__all__ = [
    "Answers",
    "render_config",
    "render_env",
    "render_launch_script",
    "find_venv",
    "venv_python",
    "required_extras",
    "run_config_wizard",
]


@dataclass
class Answers:
    """Everything the wizard needs to write a complete instance."""

    name: str = "bridge"
    backend: str = "aioc"

    # Zello
    server: str = "wss://zello.io/ws"
    channel: str = "My Channel"
    username: str = "bridge-account"
    use_token: bool = True
    use_password: bool = False

    # Direction
    zello_to_rf: bool = True
    rf_to_zello: bool = True

    # aioc backend
    input_device: str = ""
    output_device: str = ""
    sample_rate: int = 16000
    ptt_mode: str = "serial"
    tty_device: str = ""
    hid_device: str | None = None
    serial_signal: str = "dtr"
    gpio_pin: int = 3
    cos_mode: str = "internal_audio"
    cos_threshold_dbfs: float = -50.0
    cos_min_tx_ms: int = 0

    # usrp backend
    node: str = "1998"
    bind_host: str = "127.0.0.1"
    bind_port: int = 34001
    asl_host: str = "127.0.0.1"
    asl_port: int = 32001

    #: Where log output goes when nothing else is capturing it. Empty means
    #: a supervisor owns stdout -- systemd puts it in the journal.
    log_file: str = ""

    #: Secrets, kept apart from the config so they can be written 0600.
    secrets: dict[str, str] = field(default_factory=dict)

    @property
    def env_var_prefix(self) -> str:
        """Per-instance env names, so two bridges can differ on one host."""
        cleaned = "".join(c if c.isalnum() else "_" for c in self.name).upper()
        return f"ZELLO_{cleaned.strip('_')}" if cleaned.strip("_") else "ZELLO"

    @property
    def token_var(self) -> str:
        return f"{self.env_var_prefix}_AUTH_TOKEN"

    @property
    def password_var(self) -> str:
        return f"{self.env_var_prefix}_PASSWORD"


# -- rendering (pure) ------------------------------------------------------
def render_config(a: Answers) -> str:
    """The YAML for one instance. Secrets appear only as ${VAR} references."""
    out: list[str] = [
        f"# zello-link configuration for instance {a.name!r}.",
        "# Generated by `zello-link --setup`. Safe to edit by hand.",
        "#",
        "# Credentials live in the matching .env file, not here, so this file",
        "# can be shared without leaking an account.",
        "",
        "config_version: 2",
        "",
        "instance:",
        f"  name: {yaml_scalar(a.name)}",
        "  log_level: INFO",
        "",
        "zello:",
        f"  server: {yaml_scalar(a.server)}",
        f"  channel: {yaml_scalar(a.channel)}",
        f"  username: {yaml_scalar(a.username)}",
    ]
    if a.use_token:
        out.append(f'  auth_token: "${{{a.token_var}}}"')
    if a.use_password:
        out.append(f'  password: "${{{a.password_var}}}"')
    out += [
        "",
        "bridge:",
        f"  backend: {yaml_scalar(a.backend)}",
        f"  zello_to_rf: {str(a.zello_to_rf).lower()}",
        f"  rf_to_zello: {str(a.rf_to_zello).lower()}",
    ]

    if a.backend == "aioc":
        out += [
            "",
            "sound:",
            f"  input_device: {yaml_scalar(a.input_device)}",
            f"  output_device: {yaml_scalar(a.output_device)}",
            f"  sample_rate: {a.sample_rate}",
            "",
            "ptt:",
            f"  mode: {yaml_scalar(a.ptt_mode)}",
        ]
        if a.ptt_mode == "serial":
            out.append(f"  tty_device: {yaml_scalar(a.tty_device)}")
            out.append(f"  serial_signal: {yaml_scalar(a.serial_signal)}")
        elif a.ptt_mode == "cm108_hid":
            if a.hid_device:
                out.append(f"  hid_device: {yaml_scalar(a.hid_device)}")
            else:
                out.append("  # hid_device omitted: the interface is auto-detected by")
                out.append("  # USB id, which is more portable than a hardcoded path.")
            out.append(f"  gpio_pin: {a.gpio_pin}")
        out += [
            "",
            "cos:",
            f"  mode: {yaml_scalar(a.cos_mode)}",
        ]
        if a.cos_mode == "internal_audio":
            out.append(f"  threshold_dbfs: {a.cos_threshold_dbfs}")
            out.append("  hang_ms: 200")
            if a.cos_min_tx_ms:
                out.append(f"  min_tx_ms: {a.cos_min_tx_ms}")
        elif a.cos_mode == "aioc_hardware" and a.hid_device:
            out.append(f"  hid_device: {yaml_scalar(a.hid_device)}")
    else:
        out += [
            "",
            "usrp:",
            f"  bind_host: {yaml_scalar(a.bind_host)}",
            f"  bind_port: {a.bind_port}",
            f"  asl_host: {yaml_scalar(a.asl_host)}",
            f"  asl_port: {a.asl_port}",
        ]
        if a.bind_host.startswith("127."):
            out.append("")
            out.append("  # Loopback cannot reorder datagrams, so a reorder window")
            out.append("  # would be pure added latency.")
            out.append("  jitter_buffer_ms: 0")
        else:
            out.append("  allow_remote_host: true")

    out += [
        "",
        "logging:",
        "  console: true",
    ]
    if a.log_file:
        # Nothing else is capturing stdout, so persist it. A hand-started
        # instance whose terminal later closes otherwise writes every line to
        # a dead pty and loses the lot -- which is exactly how one bug's
        # evidence was lost.
        out.append(f"  file: {yaml_scalar(a.log_file)}")
        out.append("  max_bytes: 10485760")
        out.append("  backup_count: 5")
    else:
        out.append("  file: null            # stdout; the supervisor captures it")
    out += [
        "",
        "metrics:",
        "  enabled: true",
        "  interval_s: 60",
        "",
    ]
    return "\n".join(out)


def render_env(a: Answers) -> str:
    """The secrets file. Written 0600; never referenced by value in YAML."""
    lines = [
        f"# Credentials for zello-link instance {a.name!r}.",
        "# chmod 600. Do not commit this file.",
        "",
    ]
    if a.use_token:
        lines.append(f"{a.token_var}={a.secrets.get(a.token_var, '')}")
    if a.use_password:
        lines.append(f"{a.password_var}={a.secrets.get(a.password_var, '')}")
    lines.append("")
    return "\n".join(lines)


def render_launch_script(
    a: Answers, *, python: str, config_path: str, env_path: str
) -> str:
    """A launcher that sources the secrets and execs the bridge.

    ``set -a`` around the env file exports every variable in it, which is what
    the config's ${VAR} references need. ``exec`` replaces the shell so signals
    reach the bridge directly -- without it, SIGTERM would stop the wrapper
    and leave PTT asserted.
    """
    return f"""#!/usr/bin/env bash
# Launch the zello-link instance {a.name!r}.
# Generated by `zello-link --setup`.
set -euo pipefail

cd "$(dirname "$0")"

if [ ! -r {env_path!r} ]; then
    echo "missing credentials file: {env_path}" >&2
    exit 1
fi

# Export everything in the env file so the config's ${{VAR}} refs resolve.
set -a
. {env_path!r}
set +a

# exec so signals reach the bridge itself; a wrapper catching SIGTERM would
# leave the transmitter keyed.
exec {python!r} -m zello_link --config {config_path!r} "$@"
"""


# -- virtualenv ------------------------------------------------------------
def find_venv(root: Path) -> Path | None:
    """An existing virtualenv usable for this instance.

    Checks the interpreter we are already running under first: if the wizard
    was started from inside a venv, that is the one the operator meant.
    """
    if sys.prefix != sys.base_prefix:
        return Path(sys.prefix)
    for name in (".venv", "venv"):
        candidate = root / name
        if (candidate / "bin" / "python").exists():
            return candidate
    return None


def venv_python(venv: Path) -> Path:
    """The interpreter inside a venv, on either layout."""
    posix = venv / "bin" / "python"
    return posix if posix.exists() else venv / "Scripts" / "python.exe"


def required_extras(backend: str) -> list[str]:
    """Which optional dependency groups this backend actually needs.

    A USRP bridge speaks UDP and needs no audio stack at all -- installing
    PortAudio on a headless node it will never use is noise, and on some
    hosts a build failure.
    """
    return ["hardware"] if backend == "aioc" else []


def create_venv(root: Path, *, extras: list[str], echo: Any = print) -> Path:
    """Build a venv and install this project into it."""
    venv = root / ".venv"
    echo(f"  creating virtualenv at {venv}")
    subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True)
    py = venv_python(venv)

    source = _project_source()
    target = f"{source}[{','.join(extras)}]" if extras else source
    echo(f"  installing {target}")
    subprocess.run([str(py), "-m", "pip", "install", "-q", "--upgrade", "pip"], check=False)
    subprocess.run([str(py), "-m", "pip", "install", "-q", target], check=True)
    return venv


def _project_source() -> str:
    """Install from the checkout when there is one, else from the index."""
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "pyproject.toml").exists():
            return str(parent)
    return "zello-link"


# -- interactive -----------------------------------------------------------
def _echo(msg: str = "") -> None:
    print(msg, file=sys.stderr)


def _heading(step: int, total: int, title: str) -> None:
    _echo("")
    _echo(f"── {step}/{total}  {title} " + "─" * max(0, 46 - len(title)))


def _prompt_secret(title: str, hint: str = "") -> str:
    """Read a credential without echoing it, and never log the value."""
    import getpass

    if hint:
        _echo(f"\n{title}\n  {hint}")
    else:
        _echo(f"\n{title}")
    while True:
        try:
            value = getpass.getpass("  (input hidden): ").strip()
        except (EOFError, KeyboardInterrupt):
            raise SelectionAborted("cancelled") from None
        if value:
            return value
        _echo("  required")


def _audio_choices(direction: str) -> list[Choice]:
    """Devices in one direction, or an empty list if PortAudio is absent."""
    try:
        from ..audio.devices import list_devices
    except Exception:
        return []
    try:
        devices = list_devices()
    except Exception as e:
        _echo(f"  cannot list audio devices: {str(e).splitlines()[0]}")
        return []

    out: list[Choice] = []
    for d in devices:
        channels = getattr(d, f"max_{direction}_channels", 0)
        if channels:
            out.append(Choice(d.name, f"[{d.index}] {d.name}", f"{channels} ch"))
    return out


def _prompt_audio_device(title: str, direction: str, current: str) -> str:
    choices = _audio_choices(direction)
    if not choices:
        return _prompt_text(
            title, current,
            hint="no devices enumerated; type a name substring or index",
        )
    choices.append(Choice("", "type a name manually", ""))
    picked = _prompt_choice(title, choices, current)
    if picked == "":
        return _prompt_text(title, current, hint="name substring or numeric index")
    return str(picked)


def _ask_zello(a: Answers) -> None:
    a.server = _prompt_text("Zello server", a.server)
    a.channel = _prompt_text(
        "Zello channel", a.channel,
        hint="exactly as it appears in the app, including spaces and case",
    )
    a.username = _prompt_text("Zello username (the bridge's own account)", a.username)

    method = _prompt_choice(
        "Credentials",
        [
            Choice("token", "API token only", "the usual choice for a channel bot"),
            Choice("both", "API token and account password", "some channels need both"),
            Choice("password", "account password only", ""),
        ],
        "token",
    )
    a.use_token = method in ("token", "both")
    a.use_password = method in ("password", "both")

    _echo("")
    _echo("  Credentials go to a 0600 .env file, never into the YAML.")
    if a.use_token:
        a.secrets[a.token_var] = _prompt_secret(
            "Zello API token",
            "the developer token for this channel (a long JWT)",
        )
    if a.use_password:
        a.secrets[a.password_var] = _prompt_secret("Zello account password")


def _ask_directions(a: Answers) -> None:
    mode = _prompt_choice(
        "Which directions should this bridge carry?",
        [
            Choice("both", "both directions", "normal two-way bridge"),
            Choice("zello_to_rf", "Zello -> radio only", "announcements onto RF"),
            Choice("rf_to_zello", "radio -> Zello only", "monitoring a channel"),
        ],
        "both",
    )
    a.zello_to_rf = mode in ("both", "zello_to_rf")
    a.rf_to_zello = mode in ("both", "rf_to_zello")


def _ask_aioc(a: Answers) -> None:
    a.input_device = _prompt_audio_device(
        "Audio INPUT (receive audio from the radio)", "input", a.input_device
    )
    a.output_device = _prompt_audio_device(
        "Audio OUTPUT (transmit audio to the radio)", "output", a.output_device
    )

    a.ptt_mode = _prompt_choice(
        "How is PTT keyed?",
        [
            Choice("serial", "serial DTR/RTS", "AIOC, Digirig Mobile, CAT cables"),
            Choice("cm108_hid", "CM108 HID GPIO", "Digirig Lite, AIOC, generic CM108"),
            Choice("none", "never key", "receive-only bench use"),
        ],
        a.ptt_mode,
    )

    if a.ptt_mode == "serial":
        a.tty_device = _prompt_text(
            "Serial device", a.tty_device or "/dev/ttyUSB0",
            hint="prefer a /dev/serial/by-id/... path; /dev/ttyUSB0 renumbers",
        )
        a.serial_signal = _prompt_choice(
            "Which line asserts PTT?",
            [
                Choice("dtr", "DTR", "AIOC, most home-built CAT cables"),
                Choice("rts", "RTS", "Digirig Mobile"),
            ],
            a.serial_signal,
        )
    elif a.ptt_mode == "cm108_hid":
        _echo("\n  The interface is auto-detected by USB id, which is more")
        _echo("  portable than a hardcoded path.")
        a.gpio_pin = int(
            _prompt_text(
                "Which CM108 GPIO drives PTT?", a.gpio_pin,
                hint="3 for AIOC and Digirig Lite; 4 on some interfaces",
            )
        )

    if not a.rf_to_zello:
        a.cos_mode = "disabled"
        return

    from .setup_wizard import detect_cos_choices

    a.cos_mode = _prompt_choice(
        "How is receive activity detected?", detect_cos_choices(), a.cos_mode
    )
    if a.cos_mode == "internal_audio":
        _echo("\n  Calibrate later with --cos-monitor: set the threshold about")
        _echo("  5 dB above the idle noise floor of a squelched radio.")
        a.cos_threshold_dbfs = float(
            _prompt_text("COS threshold (dBFS)", a.cos_threshold_dbfs)
        )
        if _confirm("Does the radio click before speech (squelch tail)?"):
            a.cos_min_tx_ms = int(
                _prompt_text(
                    "Minimum transmission (ms)", 800,
                    hint="a little longer than the click-to-speech gap",
                )
            )


def _ask_usrp(a: Answers) -> None:
    _echo("\n  A USRP bridge is best run on the AllStarLink host itself, over")
    _echo("  loopback: chan_usrp has no authentication, and loopback also")
    _echo("  sidesteps the firewall rules that block the port.")

    if not _confirm("Is this bridge running on the AllStarLink host?"):
        a.bind_host = _prompt_text(
            "This bridge's address (ASL sends audio here)", "", hint="an address on THIS host"
        )
        a.asl_host = _prompt_text("AllStarLink host address", "")
    a.node = _prompt_text(
        "Node number for the bridge", a.node,
        hint="its OWN node, separate from your RF node -- a node has one rxchannel",
    )
    a.bind_port = _prompt_port("This bridge's UDP port (HISPORT)", a.bind_port)
    a.asl_port = _prompt_port("Asterisk's UDP port (MYPORT)", a.asl_port)


def _ask_supervision(a: Answers, root: Path) -> bool:
    """Decide how the bridge is kept running, and where its output goes.

    This matters more than it looks. A bridge started by hand writes its log
    to the terminal, and when that terminal closes the process survives with
    stdout pointing at a dead pty -- every line silently discarded. A fault
    that only appears after hours of idling then leaves no evidence at all,
    which is precisely how one bug's cause went unrecorded.

    So either a supervisor owns stdout, or the config gets a log file. Never
    neither.
    """
    if systemd_available():
        choice = _prompt_choice(
            "How should the bridge be kept running?",
            [
                Choice("systemd", "install a systemd service  (recommended)",
                       "starts at boot, restarts on failure, logs to the journal"),
                Choice("manual", "just write a launch script",
                       "you supervise it; output goes to a log file"),
            ],
            "systemd",
        )
        if choice == "systemd":
            return True
    else:
        why = (
            "not running as root" if os.geteuid() != 0
            else "systemd not detected on this host"
        )
        _echo(f"\n  No service will be installed ({why}).")

    a.log_file = str(root / f"{a.name}.log")
    _echo(f"  Logging to {a.log_file}, so output survives the terminal closing.")
    return False


def run_config_wizard(target: str | None = None) -> int:
    """Create a config, secrets file, launcher, and venv from scratch."""
    from ..config import ConfigError, load_config

    if not sys.stdin.isatty():
        _echo("--setup needs an interactive terminal.")
        return 2

    root = Path(target or ".").resolve()
    root.mkdir(parents=True, exist_ok=True)
    a = Answers()

    _echo("")
    _echo("zello-link setup")
    _echo(f"  writing into {root}")
    _echo("  Ctrl-C to abort; nothing is written until the end.")

    try:
        _heading(1, 7, "Instance")
        a.name = _prompt_text(
            "Instance name", a.name,
            hint="used for the file names, and to keep two bridges apart",
        )
        a.backend = _prompt_choice(
            "What is this bridge talking to?",
            [
                Choice("aioc", "a radio, over a USB interface",
                       "AIOC, Digirig, any CM108-class adapter"),
                Choice("usrp", "an AllStarLink node, over chan_usrp",
                       "no radio on this host"),
            ],
            a.backend,
        )

        _heading(2, 7, "Zello")
        _ask_zello(a)

        _heading(3, 7, "Direction")
        _ask_directions(a)

        _heading(4, 7, "Radio side")
        if a.backend == "aioc":
            _ask_aioc(a)
        else:
            _ask_usrp(a)

        _heading(5, 7, "Supervision")
        supervise = _ask_supervision(a, root)
    except SelectionAborted as e:
        _echo(f"\naborted: {e}")
        return 1
    except (EOFError, KeyboardInterrupt):
        _echo("\naborted")
        return 1

    _heading(6, 7, "Writing files")
    cfg_path = root / f"{a.name}.yaml"
    env_path = root / f"{a.name}.env"
    run_path = root / f"run-{a.name}.sh"

    for p in (cfg_path, env_path, run_path):
        if p.exists() and not _confirm(f"{p.name} exists. Overwrite?"):
            _echo("aborted; nothing written")
            return 1

    cfg_path.write_text(render_config(a))
    _echo(f"  wrote {cfg_path.name}")

    # 0600 before the secret goes in, not after: briefly world-readable is
    # still readable.
    fd = os.open(env_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as fh:
        fh.write(render_env(a))
    _echo(f"  wrote {env_path.name}  (mode 600)")

    _heading(7, 7, "Runtime")
    venv = find_venv(root)
    if venv is None:
        _echo("  no virtualenv found here.")
        if _confirm("Create one and install zello-link into it?"):
            try:
                venv = create_venv(root, extras=required_extras(a.backend))
            except (subprocess.CalledProcessError, OSError) as e:
                _echo(f"  venv creation failed: {e}")
                _echo("  continuing; the launcher will use the current interpreter.")
    python = str(venv_python(venv)) if venv else sys.executable

    run_path.write_text(
        render_launch_script(
            a, python=python, config_path=str(cfg_path), env_path=str(env_path)
        )
    )
    run_path.chmod(0o755)
    _echo(f"  wrote {run_path.name}")

    installed = False
    if supervise:
        import getpass as _getpass

        unit = render_systemd_unit(
            a, python=python, config_path=str(cfg_path),
            env_path=str(env_path), user=_getpass.getuser(),
        )
        installed = install_systemd_unit(unit, unit_name(a), echo=_echo)

    _echo("")
    try:
        for var, value in a.secrets.items():
            os.environ.setdefault(var, value)
        cfg = load_config(cfg_path)
    except ConfigError as e:
        _echo(f"the generated config did not validate:\n{e}")
        return 1

    warnings = cfg.warnings()
    if warnings:
        _echo(f"{len(warnings)} warning(s):")
        for w in warnings:
            _echo(f"  ! {w}")
    else:
        _echo("config validates, no warnings")

    if a.backend == "usrp":
        _echo(render_asl_instructions(
            a.bind_host, a.bind_port, a.asl_port, node=int(a.node) if a.node.isdigit() else 1998
        ))

    _echo("")
    if installed:
        _echo("Done. It is running now and will start at boot.")
        _echo(f"  systemctl status {unit_name(a)}")
        _echo(f"  journalctl -u {unit_name(a)} -f")
    else:
        _echo("Done. Start the bridge with:")
        _echo(f"  {run_path}")
        if a.log_file:
            _echo(f"  logs: {a.log_file}")
    if a.backend == "aioc" and a.cos_mode == "internal_audio":
        _echo("")
        _echo("Calibrate the COS threshold against a squelched radio first:")
        _echo(f"  {python} -m zello_link --config {cfg_path} --cos-monitor")
    return 0


# -- systemd --------------------------------------------------------------
def systemd_available() -> bool:
    """True when a unit could actually be installed and started."""
    return (
        sys.platform.startswith("linux")
        and os.geteuid() == 0
        and Path("/run/systemd/system").is_dir()
    )


def unit_name(a: Answers) -> str:
    return f"zello-link-{a.name}.service"


def render_systemd_unit(
    a: Answers, *, python: str, config_path: str, env_path: str, user: str
) -> str:
    """A unit for exactly this instance, with real paths.

    Deliberately not the ``zello-link@.service`` template in the repo: that
    hardcodes /opt/zello-link, and a wizard run from a checkout would produce
    a unit pointing at an interpreter that does not exist. The paths here are
    the ones just verified to work.

    Runs as the user who ran setup, so whatever device group membership was
    used to test the interface is the membership the service gets. Handing it
    to a fresh account is how a bridge that worked by hand fails as a service.
    """
    return f"""[Unit]
Description=zello-link bridge - {a.name}
After=network-online.target sound.target
Wants=network-online.target

[Service]
Type=simple
User={user}
EnvironmentFile={env_path}
ExecStartPre={python} -m zello_link --config {config_path} --validate
ExecStart={python} -m zello_link --config {config_path}

Restart=always
RestartSec=3

# SIGTERM runs the ordered shutdown: stop streams, stop audio, unkey PTT.
# Give it room rather than being SIGKILLed mid-unkey with the radio keyed.
KillSignal=SIGTERM
TimeoutStopSec=15

NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectKernelTunables=true
ProtectControlGroups=true
LockPersonality=true

[Install]
WantedBy=multi-user.target
"""


def install_systemd_unit(text: str, name: str, *, echo: Any = print) -> bool:
    """Write, enable and start the unit. Never raises."""
    try:
        path = Path("/etc/systemd/system") / name
        path.write_text(text)
        subprocess.run(["systemctl", "daemon-reload"], check=True)
        subprocess.run(["systemctl", "enable", "--now", name], check=True)
        echo(f"  installed and started {name}")
        return True
    except (OSError, subprocess.CalledProcessError) as e:
        echo(f"  could not install the service: {e}")
        return False
