"""The setup wizard's output.

Prompting cannot be tested; what it writes can, and that is the part that has
to be right. Every test here asserts on generated bytes: a config that loads,
a secrets file that is not the config, and a launcher that will not strand a
keyed transmitter.
"""

from __future__ import annotations

import os
import stat
import sys
from pathlib import Path

from zello_link.config import load_config
from zello_link.diagnostics.config_wizard import (
    Answers,
    find_venv,
    render_config,
    render_env,
    render_launch_script,
    required_extras,
    venv_python,
)

TOKEN = "eyJhbGciOiJSUzI1NiJ9.not-a-real-token"


def aioc_answers(**kw) -> Answers:
    a = Answers(
        name="west",
        backend="aioc",
        channel="Event Security",
        username="bridge-account",
        input_device="AIOC Audio",
        output_device="AIOC Audio",
        ptt_mode="serial",
        tty_device="/dev/serial/by-id/usb-AIOC-if00",
    )
    for k, v in kw.items():
        setattr(a, k, v)
    a.secrets[a.token_var] = TOKEN
    return a


def usrp_answers(**kw) -> Answers:
    a = Answers(name="asl", backend="usrp", channel="Net Control")
    for k, v in kw.items():
        setattr(a, k, v)
    a.secrets[a.token_var] = TOKEN
    return a


def load_rendered(a: Answers, tmp_path: Path, monkeypatch):
    """Write what the wizard would write, then load it as the bridge does."""
    for var, value in a.secrets.items():
        monkeypatch.setenv(var, value)
    p = tmp_path / f"{a.name}.yaml"
    p.write_text(render_config(a))
    return load_config(p)


class TestGeneratedConfigLoads:
    def test_aioc_config_is_valid(self, tmp_path, monkeypatch):
        cfg = load_rendered(aioc_answers(), tmp_path, monkeypatch)
        assert cfg.bridge.backend == "aioc"
        assert cfg.ptt.mode == "serial"
        assert cfg.zello.channel == "Event Security"

    def test_usrp_config_is_valid(self, tmp_path, monkeypatch):
        cfg = load_rendered(usrp_answers(), tmp_path, monkeypatch)
        assert cfg.bridge.backend == "usrp"
        assert cfg.usrp.bind_port == 34001

    def test_hid_ptt_config_is_valid_without_a_device_path(self, tmp_path, monkeypatch):
        """Auto-detection is the default, so no path is written."""
        a = aioc_answers(ptt_mode="cm108_hid", gpio_pin=4)
        cfg = load_rendered(a, tmp_path, monkeypatch)
        assert cfg.ptt.mode == "cm108_hid"
        assert cfg.ptt.hid_device is None
        assert cfg.ptt.gpio_pin == 4

    def test_rts_keying_survives_the_round_trip(self, tmp_path, monkeypatch):
        cfg = load_rendered(aioc_answers(serial_signal="rts"), tmp_path, monkeypatch)
        assert cfg.ptt.serial_signal == "rts"

    def test_one_way_bridge_is_valid(self, tmp_path, monkeypatch):
        a = aioc_answers(rf_to_zello=False, cos_mode="disabled")
        cfg = load_rendered(a, tmp_path, monkeypatch)
        assert cfg.bridge.rf_to_zello is False
        assert cfg.cos.mode == "disabled"

    def test_generated_config_has_no_warnings(self, tmp_path, monkeypatch):
        """A wizard that emits a warning on its own output is a bad wizard."""
        cfg = load_rendered(aioc_answers(), tmp_path, monkeypatch)
        assert cfg.warnings() == []


class TestSecretsStayOutOfTheConfig:
    def test_token_value_is_never_in_the_yaml(self):
        a = aioc_answers()
        assert TOKEN not in render_config(a)

    def test_yaml_refers_to_the_variable_instead(self):
        a = aioc_answers()
        assert f"${{{a.token_var}}}" in render_config(a)

    def test_env_file_carries_the_value(self):
        a = aioc_answers()
        assert f"{a.token_var}={TOKEN}" in render_env(a)

    def test_password_only_written_when_chosen(self):
        a = aioc_answers(use_token=False, use_password=True)
        a.secrets[a.password_var] = "hunter2"
        env = render_env(a)
        assert a.password_var in env
        assert a.token_var not in env

    def test_env_var_names_are_per_instance(self):
        """Two bridges on one host must not share credentials by accident."""
        assert Answers(name="west").token_var != Answers(name="east").token_var

    def test_awkward_instance_names_make_legal_variables(self):
        a = Answers(name="west-side bridge.2")
        assert a.token_var == "ZELLO_WEST_SIDE_BRIDGE_2_AUTH_TOKEN"
        assert all(c.isalnum() or c == "_" for c in a.token_var)


class TestLaunchScript:
    def _script(self, **kw):
        return render_launch_script(
            aioc_answers(), python="/opt/v/bin/python",
            config_path="/etc/zl/west.yaml", env_path="/etc/zl/west.env", **kw
        )

    def test_execs_rather_than_forking(self):
        """A wrapper that catches SIGTERM would leave the radio keyed."""
        assert "exec " in self._script()

    def test_exports_the_env_file(self):
        s = self._script()
        assert "set -a" in s and "set +a" in s

    def test_refuses_to_run_without_credentials(self):
        s = self._script()
        assert "missing credentials file" in s
        assert "exit 1" in s

    def test_passes_extra_arguments_through(self):
        """So --validate or --cos-monitor can be run via the launcher."""
        assert '"$@"' in self._script()

    def test_uses_the_venv_interpreter(self):
        assert "/opt/v/bin/python" in self._script()

    def test_is_strict(self):
        assert "set -euo pipefail" in self._script()


class TestVenvDetection:
    def test_prefers_the_interpreter_already_in_use(self, tmp_path, monkeypatch):
        monkeypatch.setattr(sys, "prefix", "/somewhere/venv")
        monkeypatch.setattr(sys, "base_prefix", "/usr")
        assert find_venv(tmp_path) == Path("/somewhere/venv")

    def test_finds_a_dot_venv_beside_the_config(self, tmp_path, monkeypatch):
        monkeypatch.setattr(sys, "prefix", "/usr")
        monkeypatch.setattr(sys, "base_prefix", "/usr")
        bin_dir = tmp_path / ".venv" / "bin"
        bin_dir.mkdir(parents=True)
        (bin_dir / "python").touch()
        assert find_venv(tmp_path) == tmp_path / ".venv"

    def test_none_when_there_is_no_venv(self, tmp_path, monkeypatch):
        monkeypatch.setattr(sys, "prefix", "/usr")
        monkeypatch.setattr(sys, "base_prefix", "/usr")
        assert find_venv(tmp_path) is None

    def test_venv_python_handles_both_layouts(self, tmp_path):
        posix = tmp_path / "bin"
        posix.mkdir()
        (posix / "python").touch()
        assert venv_python(tmp_path).name == "python"
        assert venv_python(tmp_path / "absent").name == "python.exe"


class TestRequiredExtras:
    def test_usrp_needs_no_audio_stack(self):
        """A headless USRP node should not be made to build PortAudio."""
        assert required_extras("usrp") == []

    def test_aioc_needs_the_hardware_extras(self):
        assert required_extras("aioc") == ["hardware"]


class TestEnvFilePermissions:
    def test_wizard_writes_the_env_file_unreadable_to_others(self, tmp_path):
        """Mirrors what run_config_wizard does, and why it uses os.open."""
        a = aioc_answers()
        p = tmp_path / "west.env"
        fd = os.open(p, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w") as fh:
            fh.write(render_env(a))
        mode = stat.S_IMODE(p.stat().st_mode)
        assert mode == 0o600, f"expected 600, got {mode:o}"


class TestOutputIsAlwaysCaptured:
    """A bridge must never be left writing its log into the void.

    From a live incident: an instance started by hand ran for 12 hours with
    stdout pointing at a closed terminal's pty. Every line was discarded, so
    when it stopped passing inbound audio there was nothing to diagnose from.
    Either a supervisor owns stdout, or the config names a log file.
    """

    def test_log_file_is_written_into_the_config(self):
        a = aioc_answers(log_file="/srv/zl/west.log")
        text = render_config(a)
        assert 'file: "/srv/zl/west.log"' in text

    def test_log_file_config_is_valid(self, tmp_path, monkeypatch):
        a = aioc_answers(log_file=str(tmp_path / "west.log"))
        cfg = load_rendered(a, tmp_path, monkeypatch)
        assert Path(cfg.logging.file) == tmp_path / "west.log"

    def test_log_file_gets_rotation_so_it_cannot_fill_the_disk(self):
        a = aioc_answers(log_file="/srv/zl/west.log")
        text = render_config(a)
        assert "max_bytes:" in text and "backup_count:" in text

    def test_no_log_file_means_a_supervisor_owns_stdout(self):
        """Only valid when something else is capturing it; say so in the file."""
        text = render_config(aioc_answers())
        assert "file: null" in text
        assert "supervisor captures it" in text


class TestSystemdUnit:
    def _unit(self, **kw):
        from zello_link.diagnostics.config_wizard import render_systemd_unit

        return render_systemd_unit(
            aioc_answers(), python="/opt/v/bin/python",
            config_path="/etc/zl/west.yaml", env_path="/etc/zl/west.env",
            user=kw.get("user", "pi"),
        )

    def test_uses_the_real_interpreter_path(self):
        """The repo's @.service template hardcodes /opt/zello-link.

        A wizard run from a checkout would otherwise emit a unit pointing at
        an interpreter that does not exist.
        """
        unit = self._unit()
        assert "/opt/v/bin/python -m zello_link" in unit
        assert "/opt/zello-link" not in unit

    def test_validates_before_starting(self):
        assert "--validate" in self._unit()

    def test_loads_credentials_from_the_env_file(self):
        assert "EnvironmentFile=/etc/zl/west.env" in self._unit()

    def test_sigterm_with_room_to_unkey(self):
        """SIGKILL mid-shutdown can leave the transmitter keyed."""
        unit = self._unit()
        assert "KillSignal=SIGTERM" in unit
        assert "TimeoutStopSec=15" in unit

    def test_restarts_on_failure_and_starts_at_boot(self):
        unit = self._unit()
        assert "Restart=always" in unit
        assert "WantedBy=multi-user.target" in unit

    def test_runs_as_the_user_who_ran_setup(self):
        """Device group membership tested by hand must carry to the service."""
        assert "User=pi" in self._unit(user="pi")

    def test_unit_name_is_per_instance(self):
        from zello_link.diagnostics.config_wizard import unit_name

        assert unit_name(Answers(name="west")) == "zello-link-west.service"
        assert unit_name(Answers(name="east")) != unit_name(Answers(name="west"))


class TestSystemdAvailability:
    def test_requires_root(self, monkeypatch):
        from zello_link.diagnostics import config_wizard as cw

        monkeypatch.setattr(cw.os, "geteuid", lambda: 1000)
        assert cw.systemd_available() is False

    def test_requires_systemd_to_be_running(self, monkeypatch):
        from zello_link.diagnostics import config_wizard as cw

        monkeypatch.setattr(cw.os, "geteuid", lambda: 0)
        monkeypatch.setattr(cw.sys, "platform", "darwin")
        assert cw.systemd_available() is False


class TestProtectHomeDoesNotBreakTheUnit:
    """ProtectHome hides /root and /home from the service.

    The quickstart clones into a home directory by default, so setting it
    there makes the interpreter itself unreachable: systemd fails with
    203/EXEC and Restart=always loops forever. A generated unit did exactly
    that 170 times on a live host while the operator's hand-started process
    kept working, which made it look like the service was fine.
    """

    def _unit(self, python, config, env):
        from zello_link.diagnostics.config_wizard import render_systemd_unit

        return render_systemd_unit(
            aioc_answers(), python=python, config_path=config,
            env_path=env, user="root",
        )

    def test_omitted_when_the_interpreter_is_under_root(self):
        unit = self._unit(
            "/root/zl/.venv/bin/python", "/root/zl/w.yaml", "/root/zl/w.env"
        )
        assert "ProtectHome=true" not in unit
        assert "deliberately NOT set" in unit

    def test_omitted_when_the_interpreter_is_under_home(self):
        unit = self._unit(
            "/home/pi/zl/.venv/bin/python", "/home/pi/zl/w.yaml", "/home/pi/zl/w.env"
        )
        assert "ProtectHome=true" not in unit

    def test_omitted_when_only_the_config_is_under_home(self):
        """EnvironmentFile and --config must be readable too, not just the exe."""
        unit = self._unit(
            "/opt/zl/.venv/bin/python", "/root/w.yaml", "/opt/zl/w.env"
        )
        assert "ProtectHome=true" not in unit

    def test_kept_when_nothing_lives_in_a_home_directory(self):
        """The hardening is still worth having where it costs nothing."""
        unit = self._unit(
            "/opt/zl/.venv/bin/python", "/etc/zl/w.yaml", "/etc/zl/w.env"
        )
        assert "ProtectHome=true" in unit

    def test_other_hardening_is_unaffected(self):
        unit = self._unit(
            "/root/zl/.venv/bin/python", "/root/zl/w.yaml", "/root/zl/w.env"
        )
        for directive in ("NoNewPrivileges=true", "PrivateTmp=true",
                          "ProtectKernelTunables=true", "LockPersonality=true"):
            assert directive in unit
